services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DEBUG=${DEBUG}"
      - "SECRET_KEY=${SECRET_KEY}"
      - "ALLOWED_HOSTS=${ALLOWED_HOSTS}"
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      
volumes:
  postgres_data: